const nullableString = { type: ["string", "null"] as const };

const siteLinkSchema = {
  type: "object" as const,
  properties: {
    label: { type: "string" as const },
    href: { type: "string" as const },
  },
  required: ["label", "href"],
  additionalProperties: false,
};

/** JSON Schema for OpenAI structured outputs (strict; matches BrandData). */
export const openaiBrandJsonSchema = {
  type: "object" as const,
  additionalProperties: false,
  properties: {
    companyName: nullableString,
    tagline: nullableString,
    description: nullableString,
    industry: nullableString,
    logo: nullableString,
    logoType: {
      type: ["string", "null"] as const,
      enum: ["url", "svg", "data-uri", null],
    },
    logoDark: nullableString,
    favicon: nullableString,
    ogImage: nullableString,
    primaryColor: nullableString,
    secondaryColor: nullableString,
    otherColors: {
      type: "array" as const,
      items: { type: "string" as const },
    },
    colors: {
      type: "object" as const,
      additionalProperties: false,
      properties: {
        background: nullableString,
        surface: nullableString,
        text: nullableString,
        textMuted: nullableString,
        accent: nullableString,
        border: nullableString,
        link: nullableString,
        success: nullableString,
        warning: nullableString,
        error: nullableString,
      },
      required: [
        "background",
        "surface",
        "text",
        "textMuted",
        "accent",
        "border",
        "link",
        "success",
        "warning",
        "error",
      ],
    },
    fonts: {
      type: "array" as const,
      items: { type: "string" as const },
    },
    typography: {
      type: "object" as const,
      additionalProperties: false,
      properties: {
        headingFont: nullableString,
        bodyFont: nullableString,
        baseFontSize: nullableString,
        headingWeight: nullableString,
        bodyWeight: nullableString,
        lineHeight: nullableString,
        letterSpacing: nullableString,
      },
      required: [
        "headingFont",
        "bodyFont",
        "baseFontSize",
        "headingWeight",
        "bodyWeight",
        "lineHeight",
        "letterSpacing",
      ],
    },
    customization: {
      type: "object" as const,
      additionalProperties: false,
      properties: {
        borderRadius: nullableString,
        buttonRadius: nullableString,
        spacing: nullableString,
        containerMaxWidth: nullableString,
        buttonStyle: nullableString,
        iconStyle: nullableString,
        theme: nullableString,
        shadows: nullableString,
        notes: nullableString,
      },
      required: [
        "borderRadius",
        "buttonRadius",
        "spacing",
        "containerMaxWidth",
        "buttonStyle",
        "iconStyle",
        "theme",
        "shadows",
        "notes",
      ],
    },
    navLinks: {
      type: "array" as const,
      items: siteLinkSchema,
    },
    ctas: {
      type: "array" as const,
      items: siteLinkSchema,
    },
    socialLinks: {
      type: "array" as const,
      items: {
        type: "object" as const,
        properties: {
          platform: { type: "string" as const },
          url: { type: "string" as const },
        },
        required: ["platform", "url"],
        additionalProperties: false,
      },
    },
    contact: {
      type: "object" as const,
      additionalProperties: false,
      properties: {
        email: nullableString,
        phone: nullableString,
        address: nullableString,
      },
      required: ["email", "phone", "address"],
    },
    footerText: nullableString,
    keywords: {
      type: "array" as const,
      items: { type: "string" as const },
    },
    themeColor: nullableString,
    language: nullableString,
  },
  required: [
    "companyName",
    "tagline",
    "description",
    "industry",
    "logo",
    "logoType",
    "logoDark",
    "favicon",
    "ogImage",
    "primaryColor",
    "secondaryColor",
    "otherColors",
    "colors",
    "fonts",
    "typography",
    "customization",
    "navLinks",
    "ctas",
    "socialLinks",
    "contact",
    "footerText",
    "keywords",
    "themeColor",
    "language",
  ],
};
